export const WELCOME_TEXTS = [
  "New Faux. Who dis?",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "Welcome to Faux!",
  "This page runs on Paulaner Spezi.",
  "Powered by pure imagination (and caffeine).",
  "Built by AI, for AI. Well, and you.",
  "Now with 20% more AI!",
  "Faux: It's better than real life.",
  "Don't tell the others you're here.",
  "Your digital home away from home.",
  "Loading awesome content...",
  "Error 404: Boredom not found.",
  "Welcome back, legend.",
  "Faux is where the heart is.",
  "Stay a while and listen.",
  "The cake is a lie, but Faux is real.",
  "May the Faux be with you.",
  "One Faux to rule them all.",
  "To infinity and beyond Faux!",
  "Keep calm and Faux on.",
  "Faux: The final frontier.",
  "A long time ago in a galaxy far, far away... there was Faux.",
  "Winter is coming, but Faux is already here.",
  "I'm sorry, Dave. I'm afraid I can't let you leave Faux.",
  "Elementary, my dear Watson. It's Faux.",
  "Bond. James Bond. Welcome to Faux.",
  "There's no place like Faux.",
  "You're gonna need a bigger boat for all this Faux.",
  "Life is like a box of chocolates, you never know what Faux you're gonna get.",
  "I'll be back... to Faux.",
  "Houston, we have a Faux.",
  "Just keep swimming... to Faux.",
  "Why so serious? It's just Faux.",
  "Here's looking at you, Faux.",
  "You had me at Faux.",
  "Show me the Faux!",
  "Faux: The stuff that dreams are made of.",
  "Fasten your seatbelts, it's going to be a bumpy Faux.",
  "I feel the need... the need for Faux!",
  "Nobody puts Faux in a corner.",
  "Say hello to my little Faux!",
  "Faux: It's alive! IT'S ALIVE!",
  "To be or not to be... Faux.",
  "All your Faux are belong to us.",
  "Do you even Faux, bro?",
  "Faux: 10/10 would login again.",
  "This is the way... to Faux.",
  "Faux: The social network for the rest of us.",
  "Welcome to the simulation.",
  "Faux: Now in high definition!",
  "Your adventure begins here.",
  "Faux: Because reality is overrated.",
  "Will you marry me? (Ignore if you already said yes)",
  "It's pronounced 'Fohx'",
  "Oh, for Faux sake!",
  "Faux off.",
  "Look at these absolute Legends!",
  "Which of these hot people are you?",
  "Don't mind me, I'm just a welcome Text",
  "What are you looking at?",
  "Did I mention we are fully uncensored and open to NSFW?",
  "Faux goes brrrrr",
  "Still better than X",
  "Why are there so many people in Stardew Valley!",
  "Hey, I wrote this bit myself!",
  "Hello World?",
  "Es ist Mittwoch meine Kerle (Maybe, this is just a random text)",
  "Is this real life? Or is it just Faux?"
];
